Repository MIC-TEAM/wellseecoding-front, pull requests merged in 2021-09, with the labels that each got.

#15 [wsc-017] 로그인 정보 바탕으로 함께해요 글쓰기 작업
  src/components/AuthLogin/index.tsx
  src/pages/together/write/index.tsx
Labels: feature

#17 [WSC-018] home/together 페이지 리팩토링/ 다이나믹 라우팅 구현
  package.json
  src/apis/dummyData/index.tsx
  src/components/Common/HashWrap/index.tsx
  src/components/Home/ClassList/index.tsx
  src/components/Home/StudySection/index.tsx
  src/components/Together/StudyBox/index.tsx
  src/components/Together/StudyBox/style.tsx
  src/components/Together/StudySection/index.tsx
  src/components/Together/StudySlider/index.tsx
  src/pages/post/[id].tsx
  src/pages/together/index.tsx
  src/pages/together/write/index.tsx
  yarn.lock
Labels: feature, refactoring

#19 [WSC-020] 변경사항 수정 및 함께해요 페이지 서버 데이터 적용 (GET/POST)
  package.json
  src/apis/index.tsx
  src/pages/immsi/index.tsx
  src/pages/together/write/index.tsx
  src/reducers/index.tsx
  src/reducers/posts/index.tsx
  src/sagas/index.tsx
  src/sagas/posts/index.tsx
  src/sagas/todos/index.tsx
  src/types/index.ts
  yarn.lock
Labels: feature, hotfix

#20 [WSC-019] 회원가입 유효성 검사
  src/apis/index.tsx
  src/components/Common/FooterMenu/index.tsx
  src/components/Common/PasswordField/index.tsx
  src/components/Common/TextField/index.tsx
  src/components/Post/PostFooter/index.tsx
  src/components/Together/WriteButton/index.tsx
  src/pages/post/comment/index.tsx
  src/pages/sign_up/index.tsx
  src/pages/together/index.tsx
  src/pages/together/write/index.tsx
  src/styles/global-styles.tsx
Labels: feature

#27 [WSC-023] 검색 / 랜덤 포스트 불러오기 구현 (최근 검색어 기능 포함)
  src/components/Common/Header/BackOptional/index.tsx
  src/components/Together/Header/Search/index.tsx
  src/components/Together/Header/Search/style.tsx
  src/components/Together/Header/index.tsx
  src/components/Together/Header/style.tsx
  src/components/Together/SearchBox/index.tsx
  src/components/Together/StudySection/index.tsx
  src/pages/home/index.tsx
  src/pages/immsi/index.tsx
  src/pages/index.tsx
  src/pages/sign_in/email_start/index.tsx
  src/pages/sign_in/reset_password/index.tsx
  src/pages/sign_up/experience/index.tsx
  src/pages/sign_up/portfolio/index.tsx
  src/pages/sign_up/profile_upload/index.tsx
  src/pages/sign_up/school/index.tsx
  src/pages/sign_up/self_introduction/index.tsx
  src/pages/sign_up/something_job/index.tsx
  src/pages/together/index.tsx
  src/pages/together/search/index.tsx
  src/pages/together/search_result/[id].tsx
  src/pages/together/write/index.tsx
  src/reducers/posts/index.tsx
  src/types/index.ts
  src/utils/TokenManager.tsx
Labels: bug, feature, hotfix
